In [1]:
import torch

from torch.autograd import grad

In [2]:
x = torch.autograd.Variable(torch.Tensor([2,1]),requires_grad=True)
# z = torch.autograd.Variable(torch.Tensor([1]),requires_grad=True)
# y = 5*x**4 + 3*x**3 + 7*x**2 + 9*x - 5

# y.backward()
# x.grad

In [3]:
x

tensor([2., 1.], requires_grad=True)

In [4]:
y = torch.sqrt_(x[0]**2 + x[1]**2 - 1)

In [13]:
y

tensor(2., grad_fn=<SqrtBackward>)

In [6]:

# y.backward(retain_graph=True)
# x.grad

x_1grad, = grad(y, x, create_graph=True,retain_graph=True)

In [7]:
x_1grad

tensor([1.0000, 0.5000], grad_fn=<AddBackward0>)

In [10]:

x_2grad0, = grad(x_1grad[0], x, create_graph=True)
x_2grad1, = grad(x_1grad[1], x, create_graph=True)

In [12]:
x_1grad,x_2grad0,x_2grad1

(tensor([1.0000, 0.5000], grad_fn=<AddBackward0>),
 tensor([ 0.0000, -0.2500], grad_fn=<AddBackward0>),
 tensor([-0.2500,  0.3750], grad_fn=<AddBackward0>))

In [9]:
9-3

6

In [15]:

y.backward()
x.grad

tensor([1.])

In [1]:
import torch
from torch import Tensor
from torch.autograd import Variable
from torch.autograd import grad
from torch import nn

torch.manual_seed(623)

x = Variable(torch.ones(2,1), requires_grad=True)
A = torch.FloatTensor([[1,2],[3,4]])

print(A)
print(x)

f = x.view(-1) @ A @ x
print(f)


x_1grad, = grad(f, x, create_graph=True)
print(x_1grad)
print(A @ x + A.t() @ x)

x_2grad0, = grad(x_1grad[0], x, create_graph=True)
x_2grad1, = grad(x_1grad[1], x, create_graph=True)

Hessian = torch.cat((x_2grad0, x_2grad1), dim=1)
print(Hessian)

print(A + A.t())

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.],
        [1.]], requires_grad=True)
tensor([10.], grad_fn=<SqueezeBackward3>)
tensor([[ 7.],
        [13.]], grad_fn=<AddBackward0>)
tensor([[ 7.],
        [13.]], grad_fn=<AddBackward0>)
tensor([[2., 5.],
        [5., 8.]])
tensor([[2., 5.],
        [5., 8.]])


In [2]:
f

tensor([10.], grad_fn=<SqueezeBackward3>)